language: fr
pipeline:
- name: HFTransformersNLP
  model_name: bert
  model_weights: bert-base-multilingual-cased
- name: LanguageModelTokenizer
- name: LanguageModelFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 75
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: MappingPolicy
